/* tslint:disable */
/* eslint-disable */
/**
 * free-ran-ue Console API
 * API documentation for free-ran-ue Console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiConsoleAuthenticatePost200Response
 */
export interface ApiConsoleAuthenticatePost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleAuthenticatePost200Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleAuthenticatePost401Response
 */
export interface ApiConsoleAuthenticatePost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleAuthenticatePost401Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost200Response
 */
export interface ApiConsoleGnbRegistrationPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {ApiConsoleGnbRegistrationPost200ResponseGnbInfo}
     * @memberof ApiConsoleGnbRegistrationPost200Response
     */
    'gnbInfo'?: ApiConsoleGnbRegistrationPost200ResponseGnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost200ResponseGnbInfo
 */
export interface ApiConsoleGnbRegistrationPost200ResponseGnbInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost200ResponseGnbInfo
     */
    'gnbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost200ResponseGnbInfo
     */
    'gnbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost200ResponseGnbInfo
     */
    'plmnId'?: string;
    /**
     * 
     * @type {ApiConsoleGnbRegistrationPost200ResponseGnbInfoSnssai}
     * @memberof ApiConsoleGnbRegistrationPost200ResponseGnbInfo
     */
    'snssai'?: ApiConsoleGnbRegistrationPost200ResponseGnbInfoSnssai;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost200ResponseGnbInfoSnssai
 */
export interface ApiConsoleGnbRegistrationPost200ResponseGnbInfoSnssai {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost200ResponseGnbInfoSnssai
     */
    'sst'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost200ResponseGnbInfoSnssai
     */
    'sd'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost400Response
 */
export interface ApiConsoleGnbRegistrationPost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost400Response
     */
    'message'?: string;
    /**
     * 
     * @type {ApiConsoleGnbRegistrationPost400ResponseGnbInfo}
     * @memberof ApiConsoleGnbRegistrationPost400Response
     */
    'gnbInfo'?: ApiConsoleGnbRegistrationPost400ResponseGnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost400ResponseGnbInfo
 */
export interface ApiConsoleGnbRegistrationPost400ResponseGnbInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost400ResponseGnbInfo
     */
    'gnbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost400ResponseGnbInfo
     */
    'gnbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost400ResponseGnbInfo
     */
    'plmnId'?: string;
    /**
     * 
     * @type {ApiConsoleGnbRegistrationPost400ResponseGnbInfoSnssai}
     * @memberof ApiConsoleGnbRegistrationPost400ResponseGnbInfo
     */
    'snssai'?: ApiConsoleGnbRegistrationPost400ResponseGnbInfoSnssai;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost400ResponseGnbInfoSnssai
 */
export interface ApiConsoleGnbRegistrationPost400ResponseGnbInfoSnssai {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost400ResponseGnbInfoSnssai
     */
    'sst'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost400ResponseGnbInfoSnssai
     */
    'sd'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost401Response
 */
export interface ApiConsoleGnbRegistrationPost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost401Response
     */
    'message'?: string;
    /**
     * 
     * @type {ApiConsoleGnbRegistrationPost400ResponseGnbInfo}
     * @memberof ApiConsoleGnbRegistrationPost401Response
     */
    'gnbInfo'?: ApiConsoleGnbRegistrationPost400ResponseGnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPost500Response
 */
export interface ApiConsoleGnbRegistrationPost500Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPost500Response
     */
    'message'?: string;
    /**
     * 
     * @type {ApiConsoleGnbRegistrationPost400ResponseGnbInfo}
     * @memberof ApiConsoleGnbRegistrationPost500Response
     */
    'gnbInfo'?: ApiConsoleGnbRegistrationPost400ResponseGnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbRegistrationPostRequest
 */
export interface ApiConsoleGnbRegistrationPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbRegistrationPostRequest
     */
    'ip': string;
    /**
     * 
     * @type {number}
     * @memberof ApiConsoleGnbRegistrationPostRequest
     */
    'port': number;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost200Response
 */
export interface ApiConsoleLoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost200Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost400Response
 */
export interface ApiConsoleLoginPost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost400Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost400Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost401Response
 */
export interface ApiConsoleLoginPost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost401Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost401Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost500Response
 */
export interface ApiConsoleLoginPost500Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost500Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost500Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPostRequest
 */
export interface ApiConsoleLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPostRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPostRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLogoutDelete200Response
 */
export interface ApiConsoleLogoutDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLogoutDelete200Response
     */
    'message'?: string;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Validate JWT token
         * @summary Authenticate Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleAuthenticatePost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/console/authenticate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Authenticate user and return JWT token
         * @summary User Login
         * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLoginPost: async (apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiConsoleLoginPostRequest' is not null or undefined
            assertParamExists('apiConsoleLoginPost', 'apiConsoleLoginPostRequest', apiConsoleLoginPostRequest)
            const localVarPath = `/api/console/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiConsoleLoginPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Logout current user
         * @summary User Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLogoutDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/console/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Validate JWT token
         * @summary Authenticate Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleAuthenticatePost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleAuthenticatePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleAuthenticatePost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiConsoleAuthenticatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Authenticate user and return JWT token
         * @summary User Login
         * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleLoginPost(apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleLoginPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleLoginPost(apiConsoleLoginPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiConsoleLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Logout current user
         * @summary User Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleLogoutDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleLogoutDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleLogoutDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiConsoleLogoutDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Validate JWT token
         * @summary Authenticate Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleAuthenticatePost(options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleAuthenticatePost200Response> {
            return localVarFp.apiConsoleAuthenticatePost(options).then((request) => request(axios, basePath));
        },
        /**
         * Authenticate user and return JWT token
         * @summary User Login
         * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLoginPost(apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleLoginPost200Response> {
            return localVarFp.apiConsoleLoginPost(apiConsoleLoginPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Logout current user
         * @summary User Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLogoutDelete(options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleLogoutDelete200Response> {
            return localVarFp.apiConsoleLogoutDelete(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * Validate JWT token
     * @summary Authenticate Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiConsoleAuthenticatePost(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiConsoleAuthenticatePost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Authenticate user and return JWT token
     * @summary User Login
     * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiConsoleLoginPost(apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiConsoleLoginPost(apiConsoleLoginPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Logout current user
     * @summary User Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiConsoleLogoutDelete(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiConsoleLogoutDelete(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GNBApi - axios parameter creator
 * @export
 */
export const GNBApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Register a new gNB with specified IP and port
         * @summary Register gNB
         * @param {ApiConsoleGnbRegistrationPostRequest} apiConsoleGnbRegistrationPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleGnbRegistrationPost: async (apiConsoleGnbRegistrationPostRequest: ApiConsoleGnbRegistrationPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiConsoleGnbRegistrationPostRequest' is not null or undefined
            assertParamExists('apiConsoleGnbRegistrationPost', 'apiConsoleGnbRegistrationPostRequest', apiConsoleGnbRegistrationPostRequest)
            const localVarPath = `/api/console/gnb/registration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiConsoleGnbRegistrationPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GNBApi - functional programming interface
 * @export
 */
export const GNBApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GNBApiAxiosParamCreator(configuration)
    return {
        /**
         * Register a new gNB with specified IP and port
         * @summary Register gNB
         * @param {ApiConsoleGnbRegistrationPostRequest} apiConsoleGnbRegistrationPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleGnbRegistrationPost(apiConsoleGnbRegistrationPostRequest: ApiConsoleGnbRegistrationPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleGnbRegistrationPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleGnbRegistrationPost(apiConsoleGnbRegistrationPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GNBApi.apiConsoleGnbRegistrationPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GNBApi - factory interface
 * @export
 */
export const GNBApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GNBApiFp(configuration)
    return {
        /**
         * Register a new gNB with specified IP and port
         * @summary Register gNB
         * @param {ApiConsoleGnbRegistrationPostRequest} apiConsoleGnbRegistrationPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleGnbRegistrationPost(apiConsoleGnbRegistrationPostRequest: ApiConsoleGnbRegistrationPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleGnbRegistrationPost200Response> {
            return localVarFp.apiConsoleGnbRegistrationPost(apiConsoleGnbRegistrationPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GNBApi - object-oriented interface
 * @export
 * @class GNBApi
 * @extends {BaseAPI}
 */
export class GNBApi extends BaseAPI {
    /**
     * Register a new gNB with specified IP and port
     * @summary Register gNB
     * @param {ApiConsoleGnbRegistrationPostRequest} apiConsoleGnbRegistrationPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GNBApi
     */
    public apiConsoleGnbRegistrationPost(apiConsoleGnbRegistrationPostRequest: ApiConsoleGnbRegistrationPostRequest, options?: RawAxiosRequestConfig) {
        return GNBApiFp(this.configuration).apiConsoleGnbRegistrationPost(apiConsoleGnbRegistrationPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



